name: Build Image

on:
  push:
      tags:
          - v*

jobs:
  build:
      if: github.event.base_ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      name: Build image job
      
      steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Get version
            id: get_version
            if: startsWith(github.ref, 'refs/tags/') && startsWith(github.repository, 'kouchao/TiantianFundApi')
            run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          - name: Login to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v3
            if: startsWith(github.ref, 'refs/tags/') && startsWith(github.repository, 'kouchao/TiantianFundApi')
            with:
              publish: true
              tags: kouchao/tiantian_fund_api:${{ steps.get_version.outputs.VERSION }}