name: ci
on:
  push:
    pull_request:
    branches:
      - main
jobs:
  test:
    name: 自动化测试
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.6
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm run test-reporter
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 测试报告
          path: test-results.json
          reporter: mocha-json
  deploy-doc:
    name: 部署文档
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./docs