name: deploy ppt
on:
  push:
    pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.6
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm run test-reporter
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MOCHA Tests
          path: test-results.json
          reporter: mocha-json
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./docs