name: 部署文档
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  deploy-doc:
    name: 部署文档
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./docs